import "./globals.css";
import type { Metadata } from "next";
import { Eczar } from "next/font/google";

const inter = Eczar({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="scrollbar scrollbar-w-2  scrollbar-track-whileWhhite
     scrollbar-thumb-slate-400/20 scrollbar-thumb-rounded-xl bg-whileWhite"
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
